# Generated by Django 2.2.1 on 2019-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_img',
            field=models.CharField(default='https://ibb.co/G2LHm2P', max_length=400),
        ),
    ]
