# Generated by Django 2.2.1 on 2019-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member_member_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('station', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='rating',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_img',
            field=models.CharField(default='https://i.ibb.co/G2LHm2P/1.png', max_length=200),
        ),
    ]
