# Generated by Django 2.2.1 on 2019-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190511_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_img',
            field=models.CharField(default='https://ibb.co/G2LHm2P', max_length=400),
        ),
    ]
