# Generated by Django 2.2.1 on 2019-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_station_station_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_atm', models.BooleanField()),
                ('with_terminal', models.BooleanField()),
                ('with_qiwi', models.BooleanField()),
                ('with_beeline', models.BooleanField()),
                ('with_woopay', models.BooleanField()),
            ],
        ),
    ]
