# Generated by Django 2.2.1 on 2019-05-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
