# Generated by Django 2.2.1 on 2019-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='has_beeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='has_qiwi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='has_term',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='has_woopay',
            field=models.BooleanField(default=True),
        ),
    ]
