# Generated by Django 2.2.1 on 2019-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_company_company_rate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_tel',
            field=models.CharField(default='open 24 hours', max_length=130),
        ),
        migrations.AddField(
            model_name='station',
            name='station_work_our',
            field=models.CharField(default='7242-17-65', max_length=130),
        ),
    ]
