# Generated by Django 2.2.1 on 2019-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190516_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_logo',
            field=models.CharField(default='https://ibb.co/G2LHm2P', max_length=400),
        ),
    ]
